import { StyleSheet } from 'react-native';

export const getStyles = (isSidebarVisible, isDarkMode) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: isDarkMode ? '#121212' : '#F7FAFF',
    paddingBottom: 16,
  },
  mainContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: isDarkMode ? '#121212' : '#F7FAFF',
  },
  contentContainer: {
    flex: 1,
    backgroundColor: isDarkMode ? '#121212' : '#FFFFFF',
    paddingBottom: 24,
  },
  header: {
    backgroundColor: isDarkMode ? '#2A2A2A' : 'rgba(255, 255, 255, 0.98)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: isDarkMode ? '#333' : 'rgba(79, 165, 245, 0.1)',
    shadowColor: isDarkMode ? '#333' : '#4FA5F5',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 10,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 40,
  },
  menuButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: isDarkMode ? '#333' : '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: isDarkMode ? '#333' : '#4FA5F5',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  notificationContainer: {
    position: 'absolute',
    top: 60,
    left: 20,
    right: 20,
    backgroundColor: 'transparent',
    alignItems: 'center',
    zIndex: 9999,
    paddingHorizontal: 16,
  },
  notificationContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#4FA5F5',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    minWidth: 200,
    maxWidth: '100%',
  },
  notificationSuccess: {
    backgroundColor: '#4FA5F5',
  },
  notificationError: {
    backgroundColor: '#4FA5F5',
  },
  notificationIcon: {
    marginRight: 12,
  },
  notificationText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
    textAlign: 'left',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: isDarkMode ? '#FFFFFF' : '#4FA5F5',
    letterSpacing: 0.5,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.04)' : 'rgba(79, 165, 245, 0.04)',
    padding: 6,
    borderRadius: 14,
  },
  iconButton: {
    position: 'relative',
    padding: 8,
    backgroundColor: isDarkMode ? '#333' : '#FFFFFF',
    borderRadius: 12,
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: isDarkMode ? '#333' : '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  cartBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: isDarkMode ? '#FF4B4B' : '#FF4B4B',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: isDarkMode ? '#333' : '#FFFFFF',
  },
  cartBadgeText: {
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: isDarkMode ? '#FFFFFF' : '#2D3748',
    marginVertical: 20,
    paddingHorizontal: 4,
  },
  collectionDescription: {
    fontSize: 16,
    color: isDarkMode ? '#BDC3C7' : '#555',
    marginVertical: 10,
    paddingHorizontal: 4,
    textAlign: 'center',
  },
  collectionFeatures: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
  },
  collectionFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  collectionFeatureText: {
    fontSize: 14,
    color: isDarkMode ? '#BDC3C7' : '#333',
    marginLeft: 6,
  },
  productContainer: {
    position: 'relative',
    width: '100%',
    height: 500,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
    overflow: 'hidden',
  },
  card: {
    width: '70%',
    height: 'auto',
    backgroundColor: isDarkMode ? '#333' : '#FFFFFF',
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
    padding: 10,
    marginVertical: 10,
    alignItems: 'center',
  },
  cardImageContainer: {
    width: '100%',
    height: 200,
    position: 'relative',
  },
  cardImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  badgeContainer: {
    position: 'absolute',
    top: 10,
    left: 10,
    flexDirection: 'row',
  },
  badgeNew: {
    backgroundColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    borderRadius: 4,
    padding: 4,
    marginRight: 8,
  },
  badgeBestSeller: {
    backgroundColor: isDarkMode ? '#FF4B4B' : '#FF4B4B',
    borderRadius: 4,
    padding: 4,
  },
  badgeText: {
    fontSize: 12,
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontWeight: '600',
  },
  cardContentOverlay: {
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: isDarkMode ? '#FFFFFF' : '#333',
    textAlign: 'center',
    marginVertical: 4,
  },
  cardPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: isDarkMode ? '#FFFFFF' : '#333',
    textAlign: 'center',
    marginVertical: 4,
  },
  stockStatus: {
    fontSize: 14,
    color: isDarkMode ? '#BDC3C7' : '#333',
    textAlign: 'center',
    marginVertical: 4,
  },
  quickViewButton: {
    backgroundColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    borderRadius: 12,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 40,
    height: 40,
    elevation: 2,
    marginVertical: 8,
  },
  quickViewText: {
    fontSize: 14,
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontWeight: '600',
  },
  cardRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.15)' : 'rgba(255,255,255,0.15)',
    padding: 12,
    borderRadius: 16,
    marginTop: 16,
  },
  ratingText: {
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  reviewCount: {
    fontSize: 14,
    color: isDarkMode ? '#BDC3C7' : '#BDC3C7',
    marginLeft: 8,
  },
  cardActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 10,
    marginTop: 8,
    marginBottom: 8,
  },
  favoriteButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.15)' : 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: isDarkMode ? '#333' : '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  favoriteButtonActive: {
    backgroundColor: isDarkMode ? 'rgba(255,255,255,0.9)' : 'rgba(255,255,255,0.9)',
  },
  cartButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
    overflow: 'hidden',
  },
  cartButtonSuccess: {
    backgroundColor: isDarkMode ? '#48BB78' : '#48BB78',
  },
  cartButtonContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartAnimation: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButton: {
    position: 'absolute',
    top: '50%',
    transform: [{ translateY: -25 }],
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: isDarkMode ? '#333' : '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: isDarkMode ? '#333' : '#4FA5F5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 10,
  },
  navButtonLeft: {
    left: 16,
  },
  navButtonRight: {
    right: 16,
  },
  discountItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? '#333' : '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    shadowColor: isDarkMode ? '#333' : '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  discountImageContainer: {
    width: 80,
    height: 80,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: isDarkMode ? '#444' : '#F0F0F0',
  },
  discountInfo: {
    flex: 1,
    marginLeft: 12,
  },
  discountTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: isDarkMode ? '#FFFFFF' : '#333',
    marginBottom: 4,
  },
  discountPriceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  discountPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: isDarkMode ? '#FF4B4B' : '#FF4B4B',
  },
  discountOldPrice: {
    fontSize: 14,
    color: isDarkMode ? '#BDC3C7' : '#A0AEC0',
    textDecorationLine: 'line-through',
    marginLeft: 8,
  },
  discountSavings: {
    fontSize: 12,
    color: isDarkMode ? '#48BB78' : '#48BB78',
    fontWeight: '500',
    marginTop: 2,
  },
  discountCartButton: {
    backgroundColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    borderRadius: 12,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 40,
    height: 40,
    elevation: 2,
    marginLeft: 8,
  },
  discountDescription: {
    fontSize: 12,
    color: isDarkMode ? '#BDC3C7' : '#718096',
    marginTop: 2,
  },
  discountFeatures: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
  },
  discountFeature: {
    backgroundColor: isDarkMode ? 'rgba(79, 165, 245, 0.1)' : 'rgba(79, 165, 245, 0.1)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginRight: 6,
    marginBottom: 2,
  },
  discountFeatureText: {
    color: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    fontSize: 10,
    fontWeight: '500',
  },
  viewAllButtonInline: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
    justifyContent: 'center',
    elevation: 2,
  },
  viewAllTextInline: {
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginRight: 6,
  },
  notificationContainer: {
    position: 'absolute',
    top: 100,
    left: 20,
    right: 20,
    backgroundColor: isDarkMode ? 'rgba(79, 165, 245, 0.95)' : 'rgba(79, 165, 245, 0.95)',
    borderRadius: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    zIndex: 1000,
    marginBottom: 24,
  },
  notificationContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  notificationIcon: {
    marginRight: 12,
  },
  notificationText: {
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  notificationSuccess: {
    backgroundColor: '#4FA5F5',
  },
  notificationError: {
    backgroundColor: '#4FA5F5',
  },
  notificationWarning: {
    backgroundColor: isDarkMode ? 'rgba(246, 173, 85, 0.95)' : 'rgba(246, 173, 85, 0.95)',
  },
  swipeHint: {
    position: 'absolute',
    bottom: 16,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeHintText: {
    fontSize: 14,
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    marginRight: 8,
  },
  scrollContent: {
    flexGrow: 1,
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  specialOffersHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  specialOffersTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: isDarkMode ? '#FFFFFF' : '#2D3748',
  },
  specialOffersContainer: {
    marginTop: 16,
    paddingHorizontal: 16,
  },
  specialOffersScrollContent: {
    paddingVertical: 16,
  },
  specialOfferCard: {
    width: 280,
    marginRight: 16,
    backgroundColor: isDarkMode ? '#1F1F1F' : '#FFFFFF',
    borderRadius: 12,
    shadowColor: isDarkMode ? '#000' : '#4FA5F5',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    overflow: 'hidden',
  },
  specialOfferImageContainer: {
    width: '100%',
    height: 180,
    position: 'relative',
  },
  specialOfferImage: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  discountBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: '#4FA5F5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  discountText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  specialOfferInfo: {
    padding: 16,
  },
  specialOfferName: {
    fontSize: 16,
    fontWeight: '600',
    color: isDarkMode ? '#FFFFFF' : '#1F2937',
    marginBottom: 8,
  },
  specialOfferPriceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  specialOfferPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: '#4FA5F5',
    marginRight: 8,
  },
  specialOfferOriginalPrice: {
    fontSize: 14,
    color: isDarkMode ? '#9CA3AF' : '#6B7280',
    textDecorationLine: 'line-through',
  },
  specialOfferButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4FA5F5',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  specialOfferButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    marginLeft: 8,
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: isDarkMode ? 'rgba(0,0,0,0.5)' : 'rgba(0,0,0,0.5)',
  },
  exploreButton: {
    backgroundColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
    shadowColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  exploreButtonText: {
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  tooltipContainer: {
    position: 'absolute',
    backgroundColor: isDarkMode ? 'rgba(79, 165, 245, 0.98)' : 'rgba(79, 165, 245, 0.98)',
    padding: 16,
    borderRadius: 16,
    maxWidth: 250,
    shadowColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
    zIndex: 1000,
    backdropFilter: 'blur(8px)',
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255, 255, 255, 0.2)' : 'rgba(255, 255, 255, 0.2)',
  },
  tooltipText: {
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
    fontWeight: '500',
    textShadowColor: isDarkMode ? 'rgba(0, 0, 0, 0.2)' : 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  tooltipArrow: {
    position: 'absolute',
    width: 20,
    height: 10,
    backgroundColor: isDarkMode ? 'rgba(79, 165, 245, 0.98)' : 'rgba(79, 165, 245, 0.98)',
    transform: [{ rotate: '45deg' }],
    top: -5,
    left: '50%',
    marginLeft: -10,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255, 255, 255, 0.2)' : 'rgba(255, 255, 255, 0.2)',
  },
  welcomeBannerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: isDarkMode ? 'rgba(79, 165, 245, 0.98)' : 'rgba(79, 165, 245, 0.98)',
    paddingVertical: 20,
    paddingHorizontal: 24,
    zIndex: 100,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255, 255, 255, 0.2)' : 'rgba(255, 255, 255, 0.2)',
    borderTopWidth: 0,
  },
  welcomeBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  welcomeBannerText: {
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    flex: 1,
    textShadowColor: isDarkMode ? 'rgba(0, 0, 0, 0.2)' : 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    letterSpacing: 0.5,
  },
  welcomeBannerIcon: {
    marginRight: 16,
    backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.2)' : 'rgba(255, 255, 255, 0.2)',
    padding: 10,
    borderRadius: 50,
    shadowColor: isDarkMode ? '#000' : '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  welcomeBannerClose: {
    padding: 8,
    backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.2)' : 'rgba(255, 255, 255, 0.2)',
    borderRadius: 30,
    marginLeft: 16,
  },
  guideOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: isDarkMode ? 'rgba(0, 0, 0, 0.8)' : 'rgba(0, 0, 0, 0.8)',
    zIndex: 999,
    backdropFilter: 'blur(4px)',
  },
  guideSpotlight: {
    position: 'absolute',
    backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.1)' : 'rgba(255, 255, 255, 0.1)',
    borderRadius: 100,
    zIndex: 1000,
    borderWidth: 2,
    borderColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    shadowColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  guideText: {
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 16,
    lineHeight: 24,
    textShadowColor: isDarkMode ? 'rgba(0, 0, 0, 0.3)' : 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  guideButton: {
    backgroundColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 25,
    marginTop: 16,
    shadowColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 1,
    borderColor: isDarkMode ? 'rgba(255, 255, 255, 0.3)' : 'rgba(255, 255, 255, 0.3)',
  },
  guideButtonText: {
    color: isDarkMode ? '#FFFFFF' : '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  guideProgress: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 12,
    gap: 8,
  },
  guideProgressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: isDarkMode ? 'rgba(255, 255, 255, 0.3)' : 'rgba(255, 255, 255, 0.3)',
  },
  guideProgressDotActive: {
    backgroundColor: isDarkMode ? '#4FA5F5' : '#4FA5F5',
    width: 24,
  },
  pulseAnimation: {
    position: 'absolute',
    borderRadius: 100,
  },
  tooltipIcon: {
    marginRight: 8,
  },
  themeToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 10,
    marginTop: 'auto',
    marginBottom: 20,
  },
  darkThemeToggle: {
    backgroundColor: '#2A2A2A',
  },
  lightThemeToggle: {
    backgroundColor: '#F0F0F0',
  },
  themeToggleText: {
    marginLeft: 10,
    fontSize: 16,
    fontWeight: '500',
  },
  darkText: {
    color: '#FFFFFF',
  },
  lightText: {
    color: '#000000',
  },
});
